# Generated by Django 5.0.3 on 2024-03-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='correoElectronico',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
