# Generated by Django 5.0.3 on 2024-03-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_correoelectronico_alumno_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
