# Generated by Django 5.0.3 on 2024-04-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_alumno_edad_alter_alumno_carnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(max_length=50)),
                ('codigo_banco', models.CharField(max_length=20)),
                ('fecha_pago', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.alumno')),
            ],
        ),
    ]
